### ISSUE TITLE
Exercise correction s2.7-ej05 (and help please!!)

### ISSUE THREAD

**Issue by lauraferrandof** [Adalab/soluciones-alumnas-e#11]
Hey @beatrizAdalab , can you please correct this exercise?

Also, I don't understand why this works... supposedly we had to write "numbers" as a parameter for the function, but it doesn't work if I write the function that way. I mean:

`function averageCalculator (numbers)` **DOESN'T WORK**: it says "it can't read the property length from an undefined variable" (supposedly the constant "numbers", which I defined outside the function)

`function averageCalculator ()` **WORKS**, but then I don't understand why I can put "numbers.length" as an argument when I execute the function

If you understand this problem and you have time to explain in person next week it would be really helpful!! :)

**Comment by beatrizAdalab** [comment]
Hey @lauraferrandof I can help, :) but I downloaded the repository and only the master branch appears. I can not find your exercise Could you tell me where I can see it or upload it if it's not there?
Greetings

**Comment by lauraferrandof** [comment]
@beatrizAdalab  I think you have to pull the branch in which I created my exercise as well! Try `git pull origin s2.7-ej05` in your terminal (I've never done it so I don't know if this is the procedure), and then look for the directory s2.7 in sprint-2. My exercise should be there.
Thank youuu!!
