### ISSUE TITLE
Exercise correction S1-12-ej09

### ISSUE THREAD

**Issue by garcaplay** [Adalab/soluciones-alumnas-e#4]
Hi @albahniuk I have reviewed your exercise. It is really well solved! 
But, in order to improve it, could you put the title texts centered? And, it would be recommendable to position the bootstrap stylesheet before the css stylesheet (so you can modify bootstrap properties in your css if necessary).
Anyway, it has a pretty design (with soft colors instead of blinding ones) and the code is really clean and easy to read.

Bests!

**Comment by albahniuk** [comment]
Thank you @garcaplay for checking my exercise and for your advices :)
