### ISSUE TITLE
Exercise correction s1-12-ej08 

### ISSUE THREAD

**Issue by albahniuk** [Adalab/soluciones-alumnas-e#5]
Good job @garcaplay ! the exercise is really great, you apply well Bootstrap and the exercise is well seen in all devices. Visually it looks the same than the screens of the exercise. 
I only realized one detail that you can improve: the images distort a little bit because they have a fixed height, but just something not too important because in general the exercise looks perfect, congrats :)

**Comment by garcaplay** [comment]
Thank you!!
